replicaCount: 1

image:
  repository: 0x1d1983/tplbus
  pullPolicy: IfNotPresent
  tag: "latest"

env: 
    "ASPNETCORE_ENVIRONMENT": "Production"
    "ASPNETCORE_FORWARDEDHEADERS_ENABLED": "true"
    "AzureServiceBusConfig_ConnectionString": "Endpoint=sb://<sb-namespace>.servicebus.windows.net/;SharedAccessKeyName=test-policy;SharedAccessKey=<shared-access-key>;EntityPath=test-topic"
    "AzureServiceBusConfig_Topic": "test-topic"
    "AzureServiceBusConfig_Subscription": "S1"
    "AzureServiceBusConfig_ReportInterval": 10

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

autoscaling:
  enabled: false

serviceAccount:
  create: false